app = "glp1coach-api"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8000"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 20
    soft_limit = 10
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"
    tls_skip_verify = false

[processes]
  app = "uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --workers 1 --timeout-keep-alive 65"
  worker = "python backend/worker/main.py"